server:
  port: 8002

spring:
  application:
    name: cloud-payment-server
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
      driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
      url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
  cloud:
  #注册到zookeeper地址
    zookeeper:
      connect-string: 192.168.31.100:2181,192.168.31.101:2181

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.learn.demo.entities    # 所有Entity别名类所在包